import os
import pygame
pygame.init()
pygame.display.init()
WIDTH, HEIGHT = 1600, 900
screen_width = 1600
screen_height = 900
sound_effects_slash = []
sound_effects = []
laser_attack_sound = []
laser_attack_sound1 = []
sound_effects_lowmoney = []
laser_attack_sound2 = []
inferno_attack_sound = []
death_music = []
plane_sound = []
death_sound_effects3 = []
death_sound_effects2 = []
inferno_sound = []
sound_effects_build = []
death_sound_effects1 = []
sound_effects_slow = []
sound_effects_slash_hava = []
window = pygame.display.set_mode((WIDTH, HEIGHT))

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DIRECTORY = os.path.join(BASE_DIR, "assets", "assets")
DEFAULT_DIRECTORY2 = os.path.join(BASE_DIR, "assets", "assets1")

base_filename1 = os.path.join(DEFAULT_DIRECTORY,"1_Reaper_Man_Walking_{:03d}.png")
base_filename2 = os.path.join(DEFAULT_DIRECTORY,"2_Reaper_Man_Walking_{:03d}.png")
base_filename3 = os.path.join(DEFAULT_DIRECTORY,"0_Reaper_Man_Dying_{:03d}.png")
base_filenamewwidle = os.path.join(DEFAULT_DIRECTORY,"Wizard_idle_{:03d}.png")
base_filename = os.path.join(DEFAULT_DIRECTORY,"0_Reaper_Man_Walking_{:03d}.png")
base_filenameww = os.path.join(DEFAULT_DIRECTORY,"Wizard_walk_{:03d}.png")
base_filenamep0 = os.path.join(DEFAULT_DIRECTORY,"archer_walk_{:03d}.png")
base_filenamep1 = os.path.join(DEFAULT_DIRECTORY,"archer_idlee_{:03d}.png")
base_filenamep2 = os.path.join(DEFAULT_DIRECTORY,"archer_attack_{:03d}.png")
base_filenamewwn = os.path.join(DEFAULT_DIRECTORY,"ninja1_{:03d}.png")
base_filenamewwr = os.path.join(DEFAULT_DIRECTORY,"ninja2_{:03d}.png")
base_knight_lady1 = os.path.join(DEFAULT_DIRECTORY,"knight_{:03d}.png")
base_knight_lady2 = os.path.join(DEFAULT_DIRECTORY,"knight_lady2_{:03d}.png")
base_filenamewwd = os.path.join(DEFAULT_DIRECTORY,"death_wix_{:03d}.")
base_filename3y = os.path.join(DEFAULT_DIRECTORY,"1_Reaper_Man_Dying_{:03d}.png")
base_filename3yz = os.path.join(DEFAULT_DIRECTORY,"2_Reaper_Man_Dying_{:03d}.png")
base_filename6 = os.path.join(DEFAULT_DIRECTORY,"0_Reaper_Man_Run Slashing_{:03d}.png")
base_filename3g = os.path.join(DEFAULT_DIRECTORY,"0_Golem_Dying_{:03d}.png")
base_filename9 = os.path.join(DEFAULT_DIRECTORY,"Wraith_03_Moving Forward_{:03d}.png")
base_filenamet = os.path.join(DEFAULT_DIRECTORY,"Wraith_01_Moving Forward_{:03d}.png")
base_filenameg = os.path.join(DEFAULT_DIRECTORY,"paladin_{:03d}.png")
base_filenameg2 = os.path.join(DEFAULT_DIRECTORY,"1_Golem_walking_{:03d}.png")
base_filenameg3 = os.path.join(DEFAULT_DIRECTORY,"2_Golem_walking_{:03d}.png")
base_filenameh = os.path.join(DEFAULT_DIRECTORY,"0_Fallen_Angels_Idle Blinking_{:03d}.png")
base_filenames = os.path.join(DEFAULT_DIRECTORY,"0_Fallen_Angels_Slashing_{:03d}.png")
base_filenamerr = os.path.join(DEFAULT_DIRECTORY,"0_Reaper_Man_Slashing_{:03d}.png")
base_filenameinf1 = os.path.join(DEFAULT_DIRECTORY,"Gold_{:01d}.png")
base_filenameac = os.path.join(DEFAULT_DIRECTORY,"Wraith_03_Attack_{:03d}.png")
base_filenamewalk = os.path.join(DEFAULT_DIRECTORY,"0_Fallen_Angels_Walking_{:03d}.png")
base_filenameidle = os.path.join(DEFAULT_DIRECTORY,"0_Reaper_Man_Idle_{:03d}.png")
base_ch = os.path.join(DEFAULT_DIRECTORY,"hebs_{:03d}.png")
effects = os.path.join(DEFAULT_DIRECTORY,"EXPLOSIONS{:01d}.png")
xxlfr = os.path.join(DEFAULT_DIRECTORY,"idle_{:03d}.png")
lightning = os.path.join(DEFAULT_DIRECTORY,"l{:01d}.gif")
lightningh = os.path.join(DEFAULT_DIRECTORY,"s{:01d}.gif")
fire = os.path.join(DEFAULT_DIRECTORY,"f{:01d}.gif")
firee = os.path.join(DEFAULT_DIRECTORY,"o{:01d}.gif")
uf = os.path.join(DEFAULT_DIRECTORY,"r{:01d}.gif")
po = os.path.join(DEFAULT_DIRECTORY,"p{:01d}.gif")
ufg = os.path.join(DEFAULT_DIRECTORY,"z{:01d}.gif")
xx = os.path.join(DEFAULT_DIRECTORY,"mn{:01d}.gif")
xx = os.path.join(DEFAULT_DIRECTORY,"frame_{:02d}_delay-0.04s.gif")
xxl = os.path.join(DEFAULT_DIRECTORY,"frame_{:02d}_delay-0.04.gif")
xxlf = os.path.join(DEFAULT_DIRECTORY,"frame_{:02d}_delay-0.08s.gif")
bbbb1 = os.path.join(DEFAULT_DIRECTORY,"blood1 ({:02d}).gif")
bbbb2 = os.path.join(DEFAULT_DIRECTORY,"blood2 ({:02d}).gif")
bbbb3 = os.path.join(DEFAULT_DIRECTORY,"blood3 ({:02d}).gif")
bbbb4 = os.path.join(DEFAULT_DIRECTORY,"blood4 ({:02d}).gif")
bbbb5 = os.path.join(DEFAULT_DIRECTORY,"blood5 ({:02d}).gif")
bbbb6 = os.path.join(DEFAULT_DIRECTORY,"blood6 ({:02d}).gif")
bbbb7 = os.path.join(DEFAULT_DIRECTORY,"blood7 ({:02d}).gif")
gooz = os.path.join(DEFAULT_DIRECTORY,"gooz ({:02d}).gif")
ffff = os.path.join(DEFAULT_DIRECTORY,"ff{:01d}.gif")
plane = os.path.join(DEFAULT_DIRECTORY,"w{:01d}.png")
boomy = os.path.join(DEFAULT_DIRECTORY,"frames ({:02d}).gif")
nmdd = os.path.join(DEFAULT_DIRECTORY,"nmd ({:02d}).gif")
rocc = os.path.join(DEFAULT_DIRECTORY,"das_{:02d}.png")
yyyy = os.path.join(DEFAULT_DIRECTORY,"hey ({:02d}).gif")
brrr = os.path.join(DEFAULT_DIRECTORY,"brrr ({:02d}).gif")
xxlfrl = os.path.join(DEFAULT_DIRECTORY,"lose ({:02d}).gif")
fuckboom = os.path.join(DEFAULT_DIRECTORY,"bbfuck ({:02d}).gif")
walk_ranger = os.path.join(DEFAULT_DIRECTORY,"Walking_{:03d}.png")
fly = os.path.join(DEFAULT_DIRECTORY,"Jump Loop_{:03d}.png")
flyy = os.path.join(DEFAULT_DIRECTORY,"Falling Down_{:03d}.png")
xxlfrlll = os.path.join(DEFAULT_DIRECTORY,"throwing_{:03d}.png")
xxlfrllll = os.path.join(DEFAULT_DIRECTORY,"slashing_{:03d}.png")
xxlfrllllw = os.path.join(DEFAULT_DIRECTORY,"run_slash_{:03d}.png")
xxlfrllllwr = os.path.join(DEFAULT_DIRECTORY,"run_gun_{:03d}.png")
xxlfrllllg = os.path.join(DEFAULT_DIRECTORY,"firing_{:03d}.png")
miner = os.path.join(DEFAULT_DIRECTORY,"mine ({:02d}).gif")
back = os.path.join(DEFAULT_DIRECTORY,"k{:01d}.png")
shop_window_image = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"shop.png")).convert_alpha()
lose_window_image = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"loser.png")).convert_alpha()
sound_effects_slash.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"blood1.mp3")))
sound_effects_slash.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"blood2.mp3")))
sound_effects_slash.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"blood3.mp3")))
sound_effects_slash.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"blood4.mp3")))
sound_effects_slash.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"blood5.mp3")))
sound_effects_slash.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"blood6.mp3")))
sound_effects_slash_hava.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"hava1.mp3")))
sound_effects_slash_hava.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"hava2.mp3")))
sound_effects.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"sound1.ogg")))
sound_effects.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"sound2.ogg")))
sound_effects.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"sound3.ogg")))
sound_effects.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"sound4.ogg")))
sound_effects_build.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"build_tower.ogg")))
plane_sound.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"carrier_walk.ogg")))
cannon_sound = pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"cannon_attack.ogg"))
sound_effects_lowmoney.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"upgrade_failed.ogg")))
sound_effects_slow.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"slow_sound.mp3")))
explosive_sound_effects = pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"exp_sound.ogg"))
laser_attack_sound.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"laser_attack.ogg")))
laser_attack_sound1.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"wow.mp3")))
inferno_attack_sound.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"infernoo.mp3")))
inferno_attack_sound.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"infernoo1.mp3")))
lose_sound = pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"lose_sound.wav"))
robos = pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"rrs.mp3"))
death_sound_effects1.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"death_sound.ogg")))
laser_attack_sound2.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"ss.mp3")))
death_sound_effects2.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"death_sound2.ogg")))
death_sound_effects3.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"death_sound3.ogg")))
deathbycannon = pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"deathbycannon.ogg"))
death_music.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"Shadow Fight 2 OST - TITAN Extended Download.mp3")))
infff = pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"hebb.mp3"))
inferno_sound.append(pygame.mixer.Sound(os.path.join(DEFAULT_DIRECTORY,"hebb.mp3")))
circle_image = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"circle.png")).convert_alpha()
circle_image = pygame.transform.smoothscale(circle_image, (50, 50))
alpha_value = 128
circle_image.set_alpha(alpha_value)
image_sizele = lose_window_image.get_size()
tower_image = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"teslaa.png")).convert_alpha()
tower_image = pygame.transform.scale(tower_image, (270, 300))
tower_image123 = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"archery.png")).convert_alpha()
tower_image123 = pygame.transform.scale(tower_image123, (320, 380))
ray = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"ray.png")).convert_alpha()
bb = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"Bomb.png")).convert_alpha()
bb = pygame.transform.scale(bb, (50, 50))
pro1 = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"Projectile.png")).convert_alpha()
pro1 = pygame.transform.flip(pro1, True, False)
pro1 = pygame.transform.scale(pro1, (90, 45))
pro = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"Projectile.png")).convert_alpha()
pro = pygame.transform.scale(pro, (90, 45))

tower2_image = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"tower_slow.png")).convert_alpha()
tower2_image = pygame.transform.scale(tower2_image, (130, 160))
lava_image = pygame.image.load(os.path.join(DEFAULT_DIRECTORY2,"lvl1.png")).convert_alpha()
lava_image = pygame.transform.scale(lava_image, (420 / 2.5, 420 / 2.5))
frame_0 = pygame.image.load(base_filename.format(0)).convert_alpha()
frame_width, frame_height = frame_0.get_size()
bullet_image1 = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"bb1.png")).convert_alpha()
bullet_image2 = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"bb2.png")).convert_alpha()
bullet_image1 = pygame.transform.scale(bullet_image1, (60, 60))
bullet_image2 = pygame.transform.scale(bullet_image2, (60, 60))
bullet_image3 = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"exp_bullet.png")).convert_alpha()
bullet_image3 = pygame.transform.scale(bullet_image3, (60, 60))
bullet_image4 = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"slow_bullet.png")).convert_alpha()
bullet_image4 = pygame.transform.scale(bullet_image4, (60, 60))
original_image = pygame.image.load(os.path.join(DEFAULT_DIRECTORY,"Intro_image.png")).convert_alpha()
resized_image = pygame.transform.scale(original_image, (screen_width, screen_height))
pygame.mixer.music.load(os.path.join(DEFAULT_DIRECTORY,"kro_bgmusic_t2_battle1.mp3"))
sound_channel = pygame.mixer.Channel(0) 
death_music_channel= pygame.mixer.Channel(6) 
slow_sound_channel = pygame.mixer.Channel(1)
explosive_sound_channel = pygame.mixer.Channel(2)
death_sound_channel = pygame.mixer.Channel(3)
laser_sound_channel = pygame.mixer.Channel(4)
deathbycannon_channel = pygame.mixer.Channel(5)
laser_sound_channel2 = pygame.mixer.Channel(7)
channelinf = pygame.mixer.Channel(7)
fuck = 0
animation_walk = []
for i in range(24):
    base_walk = base_filenamewalk.format(i)
    framew = pygame.image.load(base_walk).convert_alpha()
    framew = pygame.transform.smoothscale(framew, (100, 100))
    framew = pygame.transform.flip(framew, True, False)
    animation_walk.append(framew)
animation_walk_wizard = []
for i in range(24):
    base_walkw = base_filenameww.format(i)
    frameww = pygame.image.load(base_walkw).convert_alpha()
    image_sizewiz = frameww.get_size()
    wiz_walk = image_sizewiz
    frameww = pygame.transform.smoothscale(frameww, (int(image_sizewiz[0]) / 7, int(image_sizewiz[1]) / 7))
    animation_walk_wizard.append(frameww)
animation_walk_ninja = []
for i in range(24):
    base_walkwn = base_filenamewwn.format(i)
    framewwn = pygame.image.load(base_walkwn).convert_alpha()
    image_sizenin = framewwn.get_size()
    wiz_walk = image_sizenin
    framewwn = pygame.transform.smoothscale(framewwn, (int(image_sizenin[0]) / 7, int(image_sizenin[1]) / 7))
    animation_walk_ninja.append(framewwn)